version: 3

tasks:
  run:
    cmds:
      - go run . {{.CLI_ARGS}}
    silent: true

  build:
    cmds:
      - go build -o llog main.go
    silent: true

  clean:
    cmds:
      - rm -rf ./.config ./llog
    silent: true
